"""change name of table

Revision ID: 0861f0eb03e5
Revises: 22d131c677a1
Create Date: 2023-05-02 18:44:51.858204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0861f0eb03e5'
down_revision = '22d131c677a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seconds_elapsed', sa.Float(), nullable=True),
    sa.Column('climb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['climb_id'], ['climb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('screenshots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seconds_elapsed', sa.FLOAT(), nullable=True),
    sa.Column('climb_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['climb_id'], ['climb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('screenshot')
    # ### end Alembic commands ###
