"""screenshots table

Revision ID: 22d131c677a1
Revises: 7a98c48d0b70
Create Date: 2023-05-02 18:42:15.825965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d131c677a1'
down_revision = '7a98c48d0b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seconds_elapsed', sa.Float(), nullable=True),
    sa.Column('climb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['climb_id'], ['climb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screenshots')
    # ### end Alembic commands ###
