"""climbs table

Revision ID: 7a98c48d0b70
Revises: 
Create Date: 2023-05-02 18:36:39.275828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a98c48d0b70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_climb_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_climb_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_climb_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_climb_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_climb_timestamp'))
        batch_op.drop_index(batch_op.f('ix_climb_name'))
        batch_op.drop_index(batch_op.f('ix_climb_grade'))
        batch_op.drop_index(batch_op.f('ix_climb_description'))

    op.drop_table('climb')
    # ### end Alembic commands ###
