"""add private field to climb

Revision ID: 8a288ca85d67
Revises: f0e55bcab232
Create Date: 2023-07-28 16:39:33.278186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a288ca85d67'
down_revision = 'f0e55bcab232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.drop_column('private')

    # ### end Alembic commands ###
