"""add colour to climb table

Revision ID: afe27a6e1197
Revises: bbc7bf372419
Create Date: 2023-05-07 19:41:48.796017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe27a6e1197'
down_revision = 'bbc7bf372419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colour', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_climb_colour'), ['colour'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_climb_colour'))
        batch_op.drop_column('colour')

    # ### end Alembic commands ###
