"""add metrics to climb db

Revision ID: f2ab62a65d60
Revises: 8a288ca85d67
Create Date: 2023-08-13 17:06:23.024545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ab62a65d60'
down_revision = '8a288ca85d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('time_taken', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('av_time_bw_moves', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('percent_completed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('percent_completed')
        batch_op.drop_column('av_time_bw_moves')
        batch_op.drop_column('time_taken')
        batch_op.drop_column('completed')
        batch_op.drop_column('attempt')

    # ### end Alembic commands ###
